### ISSUE TITLE
Results from strings containing Unicode astral characters are not calculated correctly

### ISSUE THREAD

**Issue by revelt** [shinnn/str-indexes-of#1]
It looks like this library doesn't calculate the indexes correctly when there are Unicode astral symbols (like emoji).

Below, emoji is "worth" two character lengths, while a comma is one character. In theory, `res1` and `res2` should have the same first index, `11`.

```js
var ind = require("str-indexes-of")
var res1 = ind('some🦄 text %%_var1_%% more text %%_var2_%%.', '%%_')
console.log('res1=' + res1)
// => res1=12,33
var res2 = ind('some, text %%_var1_%% more text %%_var2_%%.', '%%_')
console.log('res2=' + res2)
// res2=11,32
```

**Comment by shinnn** [comment]
Intentional. I tried to keep the behavior of this module consistent with [`String.prototype.indexOf()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf), which also doesn't consider the Unicode astral symbols.

```js
'😁a'.indexOf('a'); //=> 2, not 1
```

If you'd like to get the result you expects,

1. Convert your string into an array of each characters using [`Array.from()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from).
2. Get all indexes of the given character from the resultant array using [`arr-indexes-of`](https://github.com/shinnn/arr-indexes-of).

```js
const arrIndexesOf = require('arr-indexes-of');

const str = '😁a';
const chars = Array.from(str); //=> [ '😁', 'a' ]

arrIndexesOf(chars, 'a'); //=> 1
```

----------

Really good question. Thanks for having an interest in this project.

**Comment by revelt** [comment]
I see! Thank you for suggestion, I'll definitely concoct something from both :)
If you don't consider supporting emoji feel free to close this issue.

**Comment by revelt** [comment]
If anybody needs Unicode support right now, I just released my own take on this, [str-indexes-of-plus](https://github.com/code-and-send/str-indexes-of-plus). It supports emoji and accepts third argument `fromIndex` as a string or natural number.

@shinnn In the end I came up with a new algorithm, single `for` loop and few variables to manage internal state and count findings. `is-natural-number` and `is-natural-number-string` are amazing by the way. Thanks a lot for creating them.
